CREATE TABLE IF NOT EXISTS `CF_VIEW` (
  `ID` bigint(20) NOT NULL,
  `FORM_ACTION` varchar(255) NOT NULL,
  `FORM_ENC_TYPE` varchar(255) NOT NULL,
  `FORM_METHOD` varchar(255) NOT NULL,
  `FORM_NAME` varchar(255) NOT NULL,
  `FORM_NO_VALIDATE` bit(1) DEFAULT NULL,
  `FORM_TARGET` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_cfy5i2d56ac1va3pexodr8d1k` (`NAME`)
) ;

CREATE TABLE IF NOT EXISTS `CF_INPUT` (
  `PK` bigint(20) NOT NULL,
  `ACCESS_KEY` varchar(32) DEFAULT NULL,
  `ACCESS_KEY_LABEL` varchar(32) DEFAULT NULL,
  `CLASS_NAME` varchar(32) DEFAULT NULL,
  `CLIENT_HEIGHT` float DEFAULT NULL,
  `CLIENT_WIDTH` float DEFAULT NULL,
  `CONTENT_EDITABLE` bit(1) DEFAULT NULL,
  `DIR` varchar(3) DEFAULT NULL,
  `DISABLED` bit(1) DEFAULT NULL,
  `DRAGGABLE` bit(1) DEFAULT NULL,
  `FORM_ACTION` varchar(32) DEFAULT NULL,
  `FORM_ENC_TYPE` varchar(32) DEFAULT NULL,
  `FORM_METHOD` varchar(32) DEFAULT NULL,
  `FORM_NAME` varchar(32) DEFAULT NULL,
  `FORM_NO_VALIDATE` bit(1) DEFAULT NULL,
  `FORM_TARGET` varchar(32) DEFAULT NULL,
  `HIDDEN` varchar(255) DEFAULT NULL,
  `ID` varchar(255) NOT NULL,
  `INNER_HTML` varchar(255) DEFAULT NULL,
  `ITEM_ID` varchar(32) DEFAULT NULL,
  `ITEM_SCOPE` bit(1) DEFAULT NULL,
  `LANG` varchar(2) DEFAULT NULL,
  `LOCAL_NAME` varchar(32) DEFAULT NULL,
  `REQUIRED` bit(1) DEFAULT NULL,
  `SPELL_CHECK` bit(1) DEFAULT NULL,
  `TAB_INDEX` bigint(20) DEFAULT NULL,
  `TAB_STOP` bit(1) DEFAULT NULL,
  `TAG_NAME` varchar(32) DEFAULT NULL,
  `TITLE` varchar(32) DEFAULT NULL,
  `VIEW_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PK`),
  KEY `FK_VIEW_INPUT` (`VIEW_ID`),
  CONSTRAINT `FK_VIEW_INPUT` FOREIGN KEY (`VIEW_ID`) REFERENCES `CF_VIEW` (`ID`)
) ;

CREATE TABLE IF NOT EXISTS `CF_INPUT_TEXT` (
  `autoCapitalize` varchar(255) DEFAULT NULL,
  `autoComplete` varchar(255) DEFAULT NULL,
  `AUTO_FOCUS` bit(1) DEFAULT NULL,
  `defaultValue` varchar(255) DEFAULT NULL,
  `maxLength` bigint(20) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `pattern` varchar(255) DEFAULT NULL,
  `placeholder` varchar(255) DEFAULT NULL,
  `readOnly` bit(1) DEFAULT NULL,
  `selectionDirection` varchar(255) DEFAULT NULL,
  `selectionEnd` bigint(20) DEFAULT NULL,
  `selectionStart` bigint(20) DEFAULT NULL,
  `size` bigint(20) DEFAULT NULL,
  `TYPE` varchar(255) NOT NULL,
  `validationMessage` varchar(255) DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `PK` bigint(20) NOT NULL,
  PRIMARY KEY (`PK`),
  CONSTRAINT `FK_INPUT_INPUT_TEXT` FOREIGN KEY (`PK`) REFERENCES `CF_INPUT` (`PK`)
) ;

CREATE TABLE IF NOT EXISTS `CF_BUTTON_ELEMENT` (
  `ID` bigint(20) NOT NULL,
  `className` varchar(255) DEFAULT NULL,
  `CONTENT` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) NOT NULL,
  `VALIDATION_MESSAGE` varchar(255) DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
  `WILL_VALIDATE` bit(1) DEFAULT NULL,
  `VIEW_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_VIEW_BUTTON_ELEMENT` (`VIEW_id`),
  CONSTRAINT `FK_VIEW_BUTTON_ELEMENT` FOREIGN KEY (`VIEW_id`) REFERENCES `CF_VIEW` (`ID`)
);



CREATE TABLE IF NOT EXISTS `CF_INPUT_EMAIL` (
  `PK` bigint(20) NOT NULL,
  PRIMARY KEY (`PK`),
  CONSTRAINT `FK_INPUT_TEXT_INPUT_EMAIL` FOREIGN KEY (`PK`) REFERENCES `CF_INPUT_TEXT` (`PK`)
) ;

CREATE TABLE IF NOT EXISTS `CF_INPUT_PASSWORD` (
  `MAX` varchar(255) NOT NULL,
  `MIN` varchar(255) NOT NULL,
  `PK` bigint(20) NOT NULL,
  PRIMARY KEY (`PK`),
  CONSTRAINT `FK_INPUT_TEXT_INPUT_PASS` FOREIGN KEY (`PK`) REFERENCES `CF_INPUT_TEXT` (`PK`)
) ;


CREATE TABLE IF NOT EXISTS `PERSON` (
  `ID` varchar(255) NOT NULL,
  `EMAIL` varchar(32) DEFAULT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(500) DEFAULT NULL,
  `PICTURE_SET` bit(1) NOT NULL,
  PRIMARY KEY (`ID`)
) ;
