CREATE TABLE IF NOT EXISTS `CF_ACT_ID_USER_AUTHORITY` (
  `ID` bigint(20) NOT NULL,
  `AUTHORITY` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_lxm6gns6rs73jomd9o14rir66` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
